modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/dmillerw/PassthroughSigns/issues"
license="All rights reserved"

[[mods]]
    modId="passthroughsigns"
    version="${file.jarVersion}"
    displayName="Passthrough Signs"
    displayURL="http://minecraft.curseforge.com/projects/passthrough-signs"
    authors="Girafi, dmillerw"
    description='''
    '''

[[dependencies.passthroughsigns]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="AFTER"
    side="BOTH"